//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<ChildPre> ChildPre { get; set; }
        public virtual DbSet<CountStatistics> CountStatistics { get; set; }
        public virtual DbSet<DocIds> DocIds { get; set; }
        public virtual DbSet<SearchContent> SearchContent { get; set; }
        public virtual DbSet<SearchedDate> SearchedDate { get; set; }
        public virtual DbSet<SourceArticles> SourceArticles { get; set; }
    }
}
