//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceArticles
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string RawText { get; set; }
        public string RawHtml { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string PublishInstitution { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public string Court { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string Url { get; set; }
        public string State { get; set; }
        public string PotencyLevel { get; set; }
        public Nullable<int> Gid { get; set; }
        public Nullable<bool> Succee { get; set; }
        public string ExtendProperty { get; set; }
        public Nullable<int> PotencyLevelType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Append { get; set; }
        public string Attachment { get; set; }
        public string Guid { get; set; }
    }
}
