//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooshu.Spider.Model
{
    using Cooshu.EntityStorage;
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// System.Data.SqlClient
    /// </summary>
    public partial class CountStatistic : DbEntity<SpiderContext, CountStatistic>
    {
    	
    	/// <summary>
    	/// System.Data.SqlClient
    	/// </summary>
    	[DisplayName("System.Data.SqlClient")]
        public System.DateTime PublicDate 
    	{ 
    		get
    		{
    			return _PublicDate;
    		}
    		set
    		{
    			AddChangedProperty("PublicDate");
    			_PublicDate = value;
    		} 
    	}
    	private System.DateTime _PublicDate;
    	
    	/// <summary>
    	/// System.Data.SqlClient
    	/// </summary>
    	[DisplayName("System.Data.SqlClient")]
        public System.DateTime RefereeDate 
    	{ 
    		get
    		{
    			return _RefereeDate;
    		}
    		set
    		{
    			AddChangedProperty("RefereeDate");
    			_RefereeDate = value;
    		} 
    	}
    	private System.DateTime _RefereeDate;
    	
    	/// <summary>
    	/// System.Data.SqlClient
    	/// </summary>
    	[DisplayName("System.Data.SqlClient")]
        public int Count 
    	{ 
    		get
    		{
    			return _Count;
    		}
    		set
    		{
    			AddChangedProperty("Count");
    			_Count = value;
    		} 
    	}
    	private int _Count;
    }
}
